### ISSUE TITLE
Create a new travel grant report template

### ISSUE THREAD

**Issue by devcer** [interledger/community-report-templates#3]
- [ ] Create a new file `travelgrantreports.md` under the templates folder
- [ ] Add the content from https://community.interledger.org/new/travelgrantreports to the above Markdown

**Comment by GriffinAnnshual** [comment]
Hi @devcer I would like to work in this issue, Can you assign it to me please?

**Comment by devcer** [comment]
Done. All the best @GriffinAnnshual

**Comment by GriffinAnnshual** [comment]
Thank you. I've made the PR.
