### ISSUE TITLE
Create a new ILP Summit virtual review template

### ISSUE THREAD

**Issue by devcer** [interledger/community-report-templates#6]
- [ ]  Create a new file `virtualreview.md` under the templates folder
- [ ]  Add the content from https://community.interledger.org/new/virtualreviews to the above Markdown file

**Comment by neelshah2409** [comment]
I would like to work on it

**Comment by vaibhavkumawat-17** [comment]
hey @devcer i would love to contribute on this issue, 
please give me chance to contribute on it .
